### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_rotate_polygon_nms)

### ISSUE THREAD

**Issue by paugalles** [yangxue0827/R2CNN_HEAD_FPN_Tensorflow#10]
1. clone the repo
2.  run docker

`docker run --rm --name tfgpu -p 5552:5552 --gpus all -it -v /Data/share:/Data/share yangxue2docker/tensorflow3_gpu_cv2_sshd:v1.0 /bin/bash`

3. In the clonned repo
`cd tools `
`python3 inference.py `

4. Get this error:

```
root@27260403fc95:/scratch/MDA000_BOAT00/DEVELOPMENT/USER_WORKSPACE/pgalles/R2CNN_HEAD_FPN_Tensorflow/tools# python inference.py
Traceback (most recent call last):
  File "inference.py", line 17, in <module>
    from libs.fast_rcnn import build_fast_rcnn
  File "../libs/fast_rcnn/build_fast_rcnn.py", line 13, in <module>
    from libs.box_utils import nms_rotate
  File "../libs/box_utils/nms_rotate.py", line 12, in <module>
    from libs.box_utils.rotate_polygon_nms import rotate_gpu_nms
ImportError: dynamic module does not define module export function (PyInit_rotate_polygon_nms)
```

I am not sure. Am I missing some steps?

**Comment by paugalles** [comment]
Compiling with `python setup.py build_ext --inplace` within the docker, solved the problem.
